
name: aseprite

on: [ workflow_dispatch, push ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      
      - name: build
        id: build
        shell: cmd
        run: call build.cmd >> $GITHUB_OUTPUT
        
      - name: Upload Release 
        id: release
        if: true
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.ASEPRITE_VERSION }}
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          files: ./aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}.zip
          body: |
            [Aseprite ${{ steps.build.outputs.ASEPRITE_VERSION }}](https://github.com/aseprite/aseprite/releases/tag/${{ steps.build.outputs.ASEPRITE_VERSION }})
      
