name: Aseprite

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build, leave empty for latest"
        required: false
      publish-release:
        description: "Publish the build as a release"
        required: true
        type: boolean

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        shell: cmd
        run: call build.cmd
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite ${{ steps.build.outputs.ASEPRITE_VERSION }}
          path: Aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          if-no-files-found: error

      - name: Publish Release
        if: ${{ inputs['publish-release'] }}
        uses: softprops/action-gh-release@v2
        with:
          files: Aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}.zip
          name: Aseprite ${{ steps.build.outputs.ASEPRITE_VERSION }}
          tag_name: "ci-${{ steps.build.outputs.ASEPRITE_VERSION }}"
